### ISSUE TITLE
Do we really need the packages install & memory-cache?

### ISSUE THREAD

**Issue by jeroentvb** [MartijnReeuwijk/meesterproef-semia#3]
https://github.com/MartijnReeuwijk/meesterproef-semia/blob/0c8e79a04a7890ac0cc9493e9d5ec770fb33ec73/package.json#L36-L37

**Comment by MartijnReeuwijk** [comment]
I used it for performance matters to speed up the site load

**Comment by MartijnReeuwijk** [comment]
Removes non used
